version: "3.8"
services:
    divvydose-profile-service:
        build:
            context: .
            dockerfile: app/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ${PWD}/app:/usr/src/app
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPATH=/usr/src/app
            - FLASK_ADDRESS=0.0.0.0
        command: [python, /usr/src/run.py]
